language: node_js
node_js: "7"
dist: trusty
deploy:
  provider: gae
  keyfile: travis-ci-lit-serviceaccount.json
  project: lit-projectunicorn
before_install:
- openssl aes-256-cbc -K $encrypted_3d20bc5e964b_key -iv $encrypted_3d20bc5e964b_iv
  -in travis-ci-lit-serviceaccount.json.enc -out travis-ci-lit-serviceaccount.json
  -d
